# Site wide configuration

title: Paul Cleary
description: Paul Cleary's Engineering Blog
logo: 120x120.gif
locale: en
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner: 
  name: Paul Cleary
  email: pcleary00@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: "120x120.gif" # 160x160 px image for author byline
  disqus-shortname: pauljamesclearygithubio


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
